frr version 10.2.1
frr defaults traditional
hostname tor
service integrated-vtysh-config
!
router bgp 64512
 bgp router-id 10.100.0.100
 bgp listen range 10.100.0.0/24 peer-group OPENPEROUTER
 neighbor OPENPEROUTER peer-group
 neighbor OPENPEROUTER remote-as 64514
 !
 address-family ipv4 unicast
  neighbor OPENPEROUTER activate
  network 172.16.1.0/24
  network 172.16.2.0/24
 exit-address-family
!
